### ISSUE TITLE
发送消息的时候会报错

### ISSUE THREAD

**Issue by boteman1314** [binarywang/weixin-java-mp-demo#87]
关注的id发送消息给公众号，虽然信息也是能够返回，但是 后台会报错， 但是发送图片却没有，

**Comment by binarywang** [comment]
请给出具体的报错信息

**Comment by yf1800** [comment]
我的情況是接收的消息是数据结构  不是纯文本信息。是xml形式的

**Comment by thinkersOne** [comment]
exceptionMessage：me.chanjar.weixin.common.error.WxErrorException: 错误代码：43004, 错误信息：需要接收者关注，微信原始报文：{"errcode":43004,"errmsg":"require subscribe rid: 5f99084b-18ab7061-4d169d08"}

  caused by : me.chanjar.weixin.common.error.WxErrorException: 错误代码：43004, 错误信息：需要接收者关注，微信原始报文：{"errcode":43004,"errmsg":"require subscribe rid: 5f99084b-18ab7061-4d169d08"}
